// tipflags.h

#ifndef _INC_TIPFLAGS
#define _INC_TIPFLAGS

#define MTBL_TIP_FLAG_NODEFFLAGS	0x0001
#define MTBL_TIP_FLAG_NOFRAME		0x0002
#define MTBL_TIP_FLAG_PERMEABLE		0x0004
#define MTBL_TIP_FLAG_GRADIENT		0x0008

#define MTBL_TIP_FLAG_SINGLELINE	0x0400
#define MTBL_TIP_FLAG_CENTER		0x0800
#define MTBL_TIP_FLAG_RIGHT			0x1000


#endif // _INC_TIPFLAGS