// export.h

#ifndef _INC_EXPORT
#define _INC_EXPORT

extern "C"
{
// Export-Fehler
#define MTE_ERR_CANCELLED 0
#define MTE_ERR_RUNNING_INSTANCE -1
#define MTE_ERR_NEW_INSTANCE -2
#define MTE_ERR_STATUS -3
#define MTE_ERR_OLE_EXCEPTION -4
#define MTE_ERR_EXCEPTION -5
#define MTE_ERR_NOT_SUBCLASSED -6
#define MTE_ERR_FILE -7
#define MTE_ERR_OPEN -8
#define MTE_ERR_INVALID_LANG -9

// Export-Flags
#define MTE_COL_HEADERS 1
#define MTE_COLORS 2
#define MTE_FONTS 4
#define MTE_GRID 8
#define MTE_SHOW_STATUS 16
#define MTE_SPLIT_ROWS 32

// Export Excel-Flags
#define MTE_EXCEL_NEW_INSTANCE 1
#define MTE_EXCEL_RUNNING_INSTANCE 2
#define MTE_EXCEL_NEW_WORKBOOK 4
#define MTE_EXCEL_NEW_WORKSHEET 8
#define MTE_EXCEL_CURRENT_POS 16
#define MTE_EXCEL_STRING_COLS_AS_TEXT 32
#define MTE_EXCEL_NULLS_AS_SPACE 64
#define MTE_EXCEL_CLOSE_WORKBOOK 128
#define MTE_EXCEL_CLOSE_INSTANCE 256
#define MTE_EXCEL_HIDE_INSTANCE 512
#define MTE_EXCEL_NO_CLIPBOARD 1024
#define MTE_EXCEL_NO_AUTO_FIT_COL 2048
#define MTE_EXCEL_NO_AUTO_FIT_ROW 4096

// Export Open-Office-Calc-Flags
#define MTE_OOCALC_NEW_WORKBOOK 4
#define MTE_OOCALC_NEW_WORKSHEET 8
#define MTE_OOCALC_CURRENT_POS 16
#define MTE_OOCALC_STRING_COLS_AS_TEXT 32
#define MTE_OOCALC_NULLS_AS_SPACE 64

// Export HTML-Flags
#define MTE_HTML_OPEN_FILE 1
#define MTE_HTML_ROW_HEIGHT 2

// Sprachen-Flags
#define MTE_LNG_GERMAN 0
#define MTE_LNG_ENGLISH 1
}

#endif // _INC_EXPORT