// MImgConst.h

#ifndef _INC_MIMGCONST
#define _INC_MIMGCONST

// Includes
#include <limits.h>

// Konstanten
#define MIMG_VERSION _T("2.5.5")

#define MIMG_TYPE_UNKNOWN 0
#define MIMG_TYPE_BMP 1
#define MIMG_TYPE_GIF 2
#define MIMG_TYPE_JPG 3
#define MIMG_TYPE_PNG 4
#define MIMG_TYPE_ICO 5
#define MIMG_TYPE_TIF 6
#define MIMG_TYPE_TGA 7
#define MIMG_TYPE_PCX 8
#define MIMG_TYPE_WBMP 9
#define MIMG_TYPE_WMF 10

#define MIMG_FRAME_ICON_SMALL -1
#define MIMG_FRAME_ICON_SMALL_4BPP -2
#define MIMG_FRAME_ICON_SMALL_8BPP -3
#define MIMG_FRAME_ICON_SMALL_24BPP -4
#define MIMG_FRAME_ICON_LARGE -5
#define MIMG_FRAME_ICON_LARGE_4BPP -6
#define MIMG_FRAME_ICON_LARGE_8BPP -7
#define MIMG_FRAME_ICON_LARGE_24BPP -8
#define MIMG_FRAME_ICON_XLARGE -9
#define MIMG_FRAME_ICON_XLARGE_4BPP -10
#define MIMG_FRAME_ICON_XLARGE_8BPP -11
#define MIMG_FRAME_ICON_XLARGE_24BPP -12
#define MIMG_FRAME_ICON_XXLARGE -13
#define MIMG_FRAME_ICON_XXLARGE_4BPP -14
#define MIMG_FRAME_ICON_XXLARGE_8BPP -15
#define MIMG_FRAME_ICON_XXLARGE_24BPP -16
#define MIMG_FRAME_ICON_MEDIUM -17
#define MIMG_FRAME_ICON_MEDIUM_4BPP -18
#define MIMG_FRAME_ICON_MEDIUM_8BPP -19
#define MIMG_FRAME_ICON_MEDIUM_24BPP -20
#define MIMG_FRAME_ICON_XXXLARGE -21
#define MIMG_FRAME_ICON_XXXLARGE_4BPP -22
#define MIMG_FRAME_ICON_XXXLARGE_8BPP -23
#define MIMG_FRAME_ICON_XXXLARGE_24BPP -24
#define MIMG_FRAME_ICON_XXXXLARGE -25
#define MIMG_FRAME_ICON_XXXXLARGE_4BPP -26
#define MIMG_FRAME_ICON_XXXXLARGE_8BPP -27
#define MIMG_FRAME_ICON_XXXXLARGE_24BPP -28

#define MIMG_COMPR_GIF_RLE 0
#define MIMG_COMPR_GIF_NONE 1
#define MIMG_COMPR_GIF_LZW 2

#define MIMG_COMPR_TIF_DEFAULT 0
#define MIMG_COMPR_TIF_NONE 1
#define MIMG_COMPR_TIF_CCITTRLE 2
#define MIMG_COMPR_TIF_CCITTFAX3 3
#define MIMG_COMPR_TIF_CCITTFAX4 4
#define MIMG_COMPR_TIF_LZW 5
#define MIMG_COMPR_TIF_JPEG 7
#define	MIMG_COMPR_TIF_PACKBITS 32773

#define MIMG_DITHER_FLOYD 0
#define MIMG_DITHER_ORDERED 1
#define MIMG_DITHER_BURKES 2
#define MIMG_DITHER_STUCKI 3
#define MIMG_DITHER_JARVIS 4
#define MIMG_DITHER_SIERRA 5
#define MIMG_DITHER_STEVENSON 6
#define MIMG_DITHER_BAYER 7

#define MIMG_RESAMPLE_NC 1
#define MIMG_RESAMPLE_BIC 2
#define MIMG_RESAMPLE_BIL 3

#define MIMG_COLOR_UNDEF ULONG_MAX

#define MIMG_FI_ICON_LARGE 1
#define MIMG_FI_ICON_SMALL 2
#define MIMG_FI_ICON_OPEN 4

#define MIMG_FI_SPECIAL_CONTROLPANEL _T("SPECIAL:CONTROLPANEL")
#define MIMG_FI_SPECIAL_FAVORITES _T("SPECIAL:FAVORITES")
#define MIMG_FI_SPECIAL_INTERNET _T("SPECIAL:INTERNET")
#define MIMG_FI_SPECIAL_MYCOMPUTER _T("SPECIAL:MYCOMPUTER")
#define MIMG_FI_SPECIAL_MYDOCUMENTS _T("SPECIAL:MYDOCUMENTS")
#define MIMG_FI_SPECIAL_NETWORK _T("SPECIAL:NETWORK")
#define MIMG_FI_SPECIAL_PRINTERS _T("SPECIAL:PRINTERS")
#define MIMG_FI_SPECIAL_PROGRAMS _T("SPECIAL:PROGRAMS")
#define MIMG_FI_SPECIAL_RECENT _T("SPECIAL:RECENT")
#define MIMG_FI_SPECIAL_RECYCLEBIN _T("SPECIAL:RECYCLEBIN")

#define MIMG_DST_NONE 0
#define MIMG_DST_DISABLED 1
#define MIMG_DST_INVERTED 2

#define MIMG_COPY_OPACITY 1

#define MIMG_DRAW_DISABLED 1
#define MIMG_DRAW_USECLIPRECT 2
#define MIMG_DRAW_INVERTED 4

#define MIMG_ALIGN_LEFT 0
#define MIMG_ALIGN_TOP 0
#define MIMG_ALIGN_RIGHT 1
#define MIMG_ALIGN_BOTTOM 2
#define MIMG_ALIGN_HCENTER 4
#define MIMG_ALIGN_VCENTER 8

#define MIMG_FLAG_PRIVATE 1

#define MIMG_SCREEN_WNDCLAREAONLY 1
#define MIMG_SCREEN_WNDFOREGROUND 2

#define MIMG_CTLCLS _T("M!Image_Control")

#define MIMG_FIT_NONE 0
#define MIMG_FIT_NORMAL 1
#define MIMG_FIT_BEST 2
#define MIMG_FIT_WIDTH 3
#define MIMG_FIT_HEIGHT 4

#define MIMG_BRUSH_NONE -1
#define MIMG_BRUSH_HORIZONTAL 0
#define MIMG_BRUSH_VERTICAL 1
#define MIMG_BRUSH_FDIAGONAL 2
#define MIMG_BRUSH_BDIAGONAL 3
#define MIMG_BRUSH_CROSS 4
#define MIMG_BRUSH_DIAGCROSS 5

#define MIMG_FLAG_NOHSCROLL 1
#define MIMG_FLAG_NOVSCROLL 2
#define MIMG_FLAG_SET_FOCUS_ON_CLICK 4

#define MIMG_SCALE_HORIZONTAL 1
#define MIMG_SCALE_VERTICAL 2
#define MIMG_SCALE_BOTH 3

#define MIMG_FONT_ENH_CLEARTYPE 256

#endif // _INC_MIMGCONST